import fs from 'node:fs/promises';
import path from 'node:path';
import { safePath, shouldIgnore, PROJECT_ROOT } from './security.js';
const MAX_RESULTS = 500;
const bounded = (value, fallback = MAX_RESULTS) => Math.max(1, Math.min(Number(value) || fallback, MAX_RESULTS));
async function getFiles(dir) { const entries = await fs.readdir(dir, { withFileTypes: true }); const files = []; for (const entry of entries) { if (shouldIgnore(entry.name)) continue; const resolved = path.join(dir, entry.name); if (entry.isDirectory()) files.push(...await getFiles(resolved)); else files.push(resolved); } return files; }
function wildcardRegex(pattern) { const normalized = String(pattern || '').replaceAll('\\', '/'); let source = '^'; for (let i = 0; i < normalized.length; i += 1) { const char = normalized[i]; if (char === '*') { if (normalized[i + 1] === '*') { source += '.*'; i += 1; } else source += '[^/]*'; } else if (char === '?') source += '[^/]'; else source += /[|\\^$+?.(){}\[\]]/.test(char) ? `\\${char}` : char; } return new RegExp(`${source}$`, 'i'); }
function literalRegex(value) { return new RegExp(String(value).replaceAll('\\', '\\\\').replaceAll('[', '\\[').replaceAll(']', '\\]'), 'i'); }
export const searchTools = {
  glob: async ({ pattern, search_dir = '.', max_results = MAX_RESULTS }) => { try { const regex = wildcardRegex(pattern); const limit = bounded(max_results); const matches = (await getFiles(safePath(search_dir))).map((file) => path.relative(PROJECT_ROOT, file).replaceAll(path.sep, '/')).filter((file) => regex.test(file) || regex.test(path.basename(file)) || (String(pattern).startsWith('**/') && wildcardRegex(String(pattern).slice(3)).test(path.basename(file)))).slice(0, limit); return JSON.stringify({ matches, count: matches.length, truncated: matches.length === limit }); } catch (error) { return JSON.stringify({ error: error.message }); } },
  grep: async ({ query, search_dir = '.', file_pattern, max_results = MAX_RESULTS, context = 0 }) => { try { let searchRegex; try { searchRegex = new RegExp(String(query), 'i'); } catch { searchRegex = literalRegex(query); } const fileRegex = file_pattern ? wildcardRegex(file_pattern) : null; const limit = bounded(max_results); const contextLines = Math.max(0, Math.min(Number(context) || 0, 20)); const results = []; for (const filePath of await getFiles(safePath(search_dir))) { const relative = path.relative(PROJECT_ROOT, filePath).replaceAll(path.sep, '/'); if (fileRegex && !fileRegex.test(relative) && !fileRegex.test(path.basename(relative))) continue; let lines; try { lines = (await fs.readFile(filePath, 'utf8')).split(/\r?\n/); } catch { continue; } for (const [index, line] of lines.entries()) { if (results.length >= limit) break; if (!searchRegex.test(line)) continue; const from = Math.max(0, index - contextLines); const to = Math.min(lines.length, index + contextLines + 1); results.push({ file: relative, line: index + 1, content: line.trim(), context: lines.slice(from, to).map((value, offset) => ({ line: from + offset + 1, content: value })) }); } if (results.length >= limit) break; } return JSON.stringify({ matches: results, total_matches: results.length, truncated: results.length === limit }); } catch (error) { return JSON.stringify({ error: `Búsqueda fallida: ${error.message}` }); } },
};
